### ISSUE TITLE
type mismatch error running examples

### ISSUE THREAD

**Issue by eyaler** [lmcinnes/hdbscan#6]
i tried running both examples on windows 8.1/python 3.4.3/anaconda 2.3.0/64-bit
i get:

Traceback (most recent call last):
  File "C:/Users/eyalg/Dropbox/python/hdbscan-example/hdbscan-example.py", line 42, in <module>
    hdb = HDBSCAN(min_cluster_size=10).fit(X)
  File "C:\Anaconda3\lib\site-packages\hdbscan\hdbscan_.py", line 322, in fit
    self._min_spanning_tree) = hdbscan(X, **self.get_params())
  File "C:\Anaconda3\lib\site-packages\hdbscan\hdbscan_.py", line 231, in hdbscan
    min_samples, metric, p)
  File "C:\Anaconda3\lib\site-packages\hdbscan\hdbscan_.py", line 96, in _hdbscan_small_kdtree
    cluster_list = get_clusters(condensed_tree, stability_dict)
  File "hdbscan/_hdbscan_tree.pyx", line 225, in hdbscan._hdbscan_tree.get_clusters (hdbscan\_hdbscan_tree.c:5268)
  File "hdbscan/_hdbscan_tree.pyx", line 257, in hdbscan._hdbscan_tree.get_clusters (hdbscan\_hdbscan_tree.c:5050)
  File "hdbscan/_hdbscan_tree.pyx", line 192, in hdbscan._hdbscan_tree.bfs_from_cluster_tree (hdbscan\_hdbscan_tree.c:4228)
ValueError: Buffer dtype mismatch, expected 'int64_t' but got 'long'

**Comment by lmcinnes** [comment]
Sorry we have limited testing on Windows (and thought we'd caught most of these errors when we did) but this seems to have slipped through. I've just pushed a commit that should fix it, unfortunately I do not currently have access to a windows machine to test. Let me know if you're still having issues after updating.

Thanks.

**Comment by eyaler** [comment]
thanks, i can confirm v0.2 solved my issue
