### ISSUE TITLE
pip install error under python 3.5

### ISSUE THREAD

**Issue by jc-healy** [lmcinnes/hdbscan#9]
I tried to pip install hdbscan in a fresh conda environment under python 3.5.  I get an odd cython error.

(py35)MacBook-Pro-03:hdbscan jchealy$ pip install hdbscan
Collecting hdbscan
  Downloading hdbscan-0.4.2.tar.gz (553kB)
    100% |████████████████████████████████| 557kB 479kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/private/var/folders/_k/3j8v2fk52w70jlrs965xk79c0000gr/T/pip-build-55_jvcgz/hdbscan/setup.py", line 4, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named 'Cython'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/_k/3j8v2fk52w70jlrs965xk79c0000gr/T/pip-build-55_jvcgz/hdbscan/setup.py", line 8, in <module>
        warnings.warn(e.message)
    AttributeError: 'ImportError' object has no attribute 'message'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_k/3j8v2fk52w70jlrs965xk79c0000gr/T/pip-build-55_jvcgz/hdbscan

**Comment by jc-healy** [comment]
I can fix this by:
conda install cython
conda install numpy 
conda install scikit-learn

I just assumed that pip should pull the dependencies.  Is that a pip problem or are we not specifying the requirements correctly?

**Comment by jc-healy** [comment]
Hmmm... in order to reproduce this I took a fresh install of anaconda3.  Started up a fresh empty environment and tried pip install hdbscan.  No problems at all.

**Comment by jc-healy** [comment]
Seems to be a problem with the requirements.txt file.  I'll figure it out and fix it.

**Comment by jc-healy** [comment]
Having some problems with the dependency tree using pip to install scipy.  A slightly easier method of getting an environment conducive to install hdbscan is:
conda create -n myCondaEnvironment scikit-learn cython numpy
That will give you all the dependencies quickly and easily without messing with pip and scipy.  

I'll keep hacking away at getting pip to work without depending so heavily on conda.

**Comment by plablo09** [comment]
FWIW, when I first installed through pip I had to manualy install cython, otherwise I got some dependency errors
